language: c++
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository -y ppa:softus-team/ppa
  - sudo apt-get update -q
  - sudo apt-get install -y libboost-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libqt5opengl5-dev libqt5gstreamer-1.0-0 libqt5gstreamer-dev qttools5-dev-tools qt5-default libqt5x11extras5-dev
script:
   - cp docs/* debian/
   - dpkg-buildpackage -us -uc -I.git -I*.sh -rfakeroot

